FROM alpine:latest 
#alpine:3.12.3 - 2020.12.31
LABEL maintainer="NexCloud Peter <peter@nexclipper.io>"

RUN apk add --no-cache --update git bash unzip curl openssh-server openssh-client openrc jq
#RUN apk add --no-cache --update gcc musl-dev make openssh-keygen
#RUN apk add --no-cache --update curl unzip openssh-server openrc jq bash
